### ISSUE TITLE
Lazagne 2.4.3 Error on Mac

### ISSUE THREAD

**Issue by galeka** [AlessandroZ/LaZagne#431]
Hi,

I find this error when running Lazagne 2.4.3 on Mac

```
$ ./laZagne.py
./laZagne.py: line 12: import: command not found
./laZagne.py: line 13: import: command not found
./laZagne.py: line 14: import: command not found
./laZagne.py: line 15: import: command not found
./laZagne.py: line 16: import: command not found
from: can't read /var/mail/lazagne.config.write_output
from: can't read /var/mail/lazagne.config.manage_modules
from: can't read /var/mail/lazagne.config.constant
from: can't read /var/mail/lazagne.config.run
./laZagne.py: line 26: syntax error near unexpected token `('
./laZagne.py: line 26: `constant.st = StandardOutput(
```

Did I execute wrong file?

**Comment by plonibarploni** [comment]
It looks like since you're executing it directly from the terminal, it's treating it as a shell script.

Try `python laZagne.py`.

**Comment by galeka** [comment]
> It looks like since you're executing it directly from the terminal, it's treating it as a shell script.
> 
> Try `python laZagne.py`.

Hi, thanks for reply.

This is the error if I run "python laZagne.py"


```
$ python lazagne.py 
Traceback (most recent call last):
  File "lazagne.py", line 20, in <module>
    from lazagne.config.manage_modules import get_categories
  File "/Users/galih.putra/Downloads/LaZagne-2.4.3/Mac/lazagne/config/manage_modules.py", line 13, in <module>
    from lazagne.softwares.system.chainbreaker import ChainBreaker
  File "/Users/galih.putra/Downloads/LaZagne-2.4.3/Mac/lazagne/softwares/system/chainbreaker.py", line 11, in <module>
    from lazagne.softwares.system.chainbreaker_module.chainbreaker import *
  File "/Users/galih.putra/Downloads/LaZagne-2.4.3/Mac/lazagne/softwares/system/chainbreaker_module/chainbreaker.py", line 27, in <module>
    from .pbkdf2 import pbkdf2
  File "/Users/galih.putra/Downloads/LaZagne-2.4.3/Mac/lazagne/softwares/system/chainbreaker_module/pbkdf2.py", line 9, in <module>
    import sha
ModuleNotFoundError: No module named 'sha'
```

**Comment by plonibarploni** [comment]
Did you install the [requirements](https://github.com/AlessandroZ/LaZagne#installation)?

**Comment by galeka** [comment]
> Did you install the [requirements](https://github.com/AlessandroZ/LaZagne#installation)?

This is the result if I run "pip install -r requirements.txt"

`$ pip install -r requirements.txt
Ignoring enum34: markers 'python_version < "3.4" and sys_platform == "win32"' don't match your environment
Ignoring psutil: markers 'sys_platform == "linux" or sys_platform == "linux2"' don't match your environment
Ignoring rsa: markers 'sys_platform == "win32"' don't match your environment
Ignoring secretstorage: markers 'sys_platform == "linux" or sys_platform == "linux2"' don't match your environment
Ignoring None: markers 'sys_platform == "win32"' don't match your environment
Requirement already satisfied: pyasn1 in /anaconda3/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (0.4.7)`

Requirement already satisfied --> is it means all requirement installed?

**Comment by plonibarploni** [comment]
Yes. It might be that your python installation is corrupted, but in any case the `sha` module is deprecated. I don't have a Mac to test it on; would you mind testing https://github.com/plonibarploni/LaZagne/tree/remove-sha and let me know if it works?

**Comment by babyj3sus** [comment]
So I was actually running into the same issue, and I tried your suggestion and got this error below.

XXXXXXX$ python laZagne.py all
Traceback (most recent call last):
  File "laZagne.py", line 20, in <module>
    from lazagne.config.manage_modules import get_categories
  File "/Users/XXXX/LaZagne/Mac/lazagne/config/manage_modules.py", line 13, in <module>
    from lazagne.softwares.system.chainbreaker import ChainBreaker
  File "/Users/XXXXXX/LaZagne/Mac/lazagne/softwares/system/chainbreaker.py", line 11, in <module>
    from lazagne.softwares.system.chainbreaker_module.chainbreaker import *
  File "/Users/XXXXX/LaZagne/Mac/lazagne/softwares/system/chainbreaker_module/chainbreaker.py", line 27, in <module>
    from .pbkdf2 import pbkdf2
  File "/Users/XXXXXXXXX/LaZagne/Mac/lazagne/softwares/system/chainbreaker_module/pbkdf2.py", line 9, in <module>
    import sha
ModuleNotFoundError: No module named 'sha'

**Comment by plonibarploni** [comment]
@babyj3sus Please can you try https://github.com/plonibarploni/LaZagne/tree/remove-sha and let me know if it works?

**Comment by galeka** [comment]
> @babyj3sus Please can you try https://github.com/plonibarploni/LaZagne/tree/remove-sha and let me know if it works?

got another error

```
$ python laZagne.py
Traceback (most recent call last):
  File "laZagne.py", line 20, in <module>
    from lazagne.config.manage_modules import get_categories
  File "/Users/xx/Downloads/LaZagne-remove-sha/Mac/lazagne/config/manage_modules.py", line 13, in <module>
    from lazagne.softwares.system.chainbreaker import ChainBreaker
  File "/Users/xx/Downloads/LaZagne-remove-sha/Mac/lazagne/softwares/system/chainbreaker.py", line 11, in <module>
    from lazagne.softwares.system.chainbreaker_module.chainbreaker import *
  File "/Users/xx/Downloads/LaZagne-remove-sha/Mac/lazagne/softwares/system/chainbreaker_module/chainbreaker.py", line 27, in <module>
    from .pbkdf2 import pbkdf2
  File "/Users/xx/Downloads/LaZagne-remove-sha/Mac/lazagne/softwares/system/chainbreaker_module/pbkdf2.py", line 18, in <module>
    def pbkdf2(password, salt, itercount, keylen, hashfn=sha):
NameError: name 'sha' is not defined
```

**Comment by plonibarploni** [comment]
@galeka I just fixed that. Please let me know if it works now.

**Comment by infamousjoeg** [comment]
```shell
$ pipenv run pip freeze
pyasn1==0.4.7

$ python ./Mac/laZagne.py -i all
Traceback (most recent call last):
  File "./Mac/laZagne.py", line 20, in <module>
    from lazagne.config.manage_modules import get_categories
  File "/Users/joegarcia/Git/infamousjoeg/LaZagne/Mac/lazagne/config/manage_modules.py", line 13, in <module>
    from lazagne.softwares.system.chainbreaker import ChainBreaker
  File "/Users/joegarcia/Git/infamousjoeg/LaZagne/Mac/lazagne/softwares/system/chainbreaker.py", line 11, in <module>
    from lazagne.softwares.system.chainbreaker_module.chainbreaker import *
  File "/Users/joegarcia/Git/infamousjoeg/LaZagne/Mac/lazagne/softwares/system/chainbreaker_module/chainbreaker.py", line 27, in <module>
    from .pbkdf2 import pbkdf2
  File "/Users/joegarcia/Git/infamousjoeg/LaZagne/Mac/lazagne/softwares/system/chainbreaker_module/pbkdf2.py", line 9, in <module>
    import sha
ModuleNotFoundError: No module named 'sha'
```

@plonibarploni - assuming your `remove-sha` branch was merged into Master since I don't see it anymore, the Master branch is still failing on Mac with the above error regarding a `sha` dependency.

**Comment by infamousjoeg** [comment]
@plonibarploni Ah, I see it's a fork... let me give your fork a try.  Standby...

**Comment by infamousjoeg** [comment]
Here is the error returned on the `remove-sha` branch of your fork, @plonibarploni:

```shell
$ git checkout remove-sha
Already on 'remove-sha'
Your branch is up to date with 'origin/remove-sha'.

$ pipenv run pip freeze
pyasn1==0.4.7

$ python ./Mac/laZagne.py -i all
Traceback (most recent call last):
  File "./Mac/laZagne.py", line 195, in <module>
    dic = dict(dic.items() + dic_tmp.items())
TypeError: unsupported operand type(s) for +: 'dict_items' and 'dict_items'
```

**Comment by plonibarploni** [comment]
@infamousjoeg That error should be fixed now. I don't have a Mac to test it on, so I can't verify that it works now. Please let me me know if you try it and it works.

**Comment by infamousjoeg** [comment]
@plonibarploni Ran a test and received the following:

```shell
$ python ./Mac/laZagne.py -i all
Traceback (most recent call last):
  File "./Mac/laZagne.py", line 196, in <module>
    dic = dict(dic.items() + dic_tmp.items())
TypeError: unsupported operand type(s) for +: 'dict_items' and 'dict_items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./Mac/laZagne.py", line 198, in <module>
    dic = dict(dic.items() | dic_tmp.items())
TypeError: unhashable type: 'dict'
```

This may help: https://stackoverflow.com/a/13264725

**Comment by galeka** [comment]
This is the error i got using "LaZagne-remove-sha" package

```
Galih:Mac putrag$ cd /Users/putrag/Downloads/LaZagne-remove-sha/Mac
Galih:Mac putrag$ ls
laZagne.py	lazagne
Galih:Mac putrag$ python laZagne.py
Traceback (most recent call last):
  File "laZagne.py", line 20, in <module>
    from lazagne.config.manage_modules import get_categories
  File "/Users/putrag/Downloads/LaZagne-remove-sha/Mac/lazagne/config/manage_modules.py", line 5, in <module>
    from lazagne.softwares.browsers.mozilla import firefox_browsers
  File "/Users/putrag/Downloads/LaZagne-remove-sha/Mac/lazagne/softwares/browsers/mozilla.py", line 16, in <module>
    from pyasn1.codec.der import decoder
ImportError: No module named pyasn1.codec.der
```

Do i need to install additional module?

**Comment by Professor833** [comment]
> > It looks like since you're executing it directly from the terminal, it's treating it as a shell script.
> > Try `python laZagne.py`.
> 
> Hi, thanks for reply.
> 
> This is the error if I run "python laZagne.py"
> 
> ```
> $ python lazagne.py 
> Traceback (most recent call last):
>   File "lazagne.py", line 20, in <module>
>     from lazagne.config.manage_modules import get_categories
>   File "/Users/xx/Downloads/LaZagne-2.4.3/Mac/lazagne/config/manage_modules.py", line 13, in <module>
>     from lazagne.softwares.system.chainbreaker import ChainBreaker
>   File "/Users/xx/Downloads/LaZagne-2.4.3/Mac/lazagne/softwares/system/chainbreaker.py", line 11, in <module>
>     from lazagne.softwares.system.chainbreaker_module.chainbreaker import *
>   File "/Users/xx/Downloads/LaZagne-2.4.3/Mac/lazagne/softwares/system/chainbreaker_module/chainbreaker.py", line 27, in <module>
>     from .pbkdf2 import pbkdf2
>   File "/Users/xx/Downloads/LaZagne-2.4.3/Mac/lazagne/softwares/system/chainbreaker_module/pbkdf2.py", line 9, in <module>
>     import sha
> ModuleNotFoundError: No module named 'sha'
> ```

that's probably because 'sha' module has been depricated

**Comment by cclauss** [comment]
https://docs.python.org/2/library/sha.html is in Py2 but has been moved into hashlib in Py3.

Please try:
* `python2 laZagne.py`
* `python3 laZagne.py`

And when reporting bugs here, please be clear about which Python version you were running under.

Pupy has been holding this repo from migrating to Python 3 but hopefully, that will change soon.
